# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/sw/PLE/workspace/lixy1/tickets/PLE-17641/bfx_extend_houdini/bfx_hou/tools/hda_shop/designer/mainWindow_new.ui'
#
# Created: Wed Sep 21 10:15:36 2022
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!


from BQt import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_add_menu = QtWidgets.QLabel(self.centralwidget)
        self.label_add_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_menu.setObjectName("label_add_menu")
        self.gridLayout_3.addWidget(self.label_add_menu, 1, 2, 1, 1)
        self.label_help = QtWidgets.QLabel(self.centralwidget)
        self.label_help.setAlignment(QtCore.Qt.AlignCenter)
        self.label_help.setObjectName("label_help")
        self.gridLayout_3.addWidget(self.label_help, 1, 5, 1, 1)
        self.button_help = QtWidgets.QPushButton(self.centralwidget)
        self.button_help.setText("")
        self.button_help.setIconSize(QtCore.QSize(36, 36))
        self.button_help.setFlat(True)
        self.button_help.setObjectName("button_help")
        self.gridLayout_3.addWidget(self.button_help, 0, 5, 1, 1)
        self.label_update = QtWidgets.QLabel(self.centralwidget)
        self.label_update.setAlignment(QtCore.Qt.AlignCenter)
        self.label_update.setObjectName("label_update")
        self.gridLayout_3.addWidget(self.label_update, 1, 6, 1, 1)
        self.button_add_HDA = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_HDA.setText("")
        self.button_add_HDA.setIconSize(QtCore.QSize(36, 36))
        self.button_add_HDA.setFlat(True)
        self.button_add_HDA.setObjectName("button_add_HDA")
        self.gridLayout_3.addWidget(self.button_add_HDA, 0, 0, 1, 1)
        self.label_upload_HDA = QtWidgets.QLabel(self.centralwidget)
        self.label_upload_HDA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_upload_HDA.setObjectName("label_upload_HDA")
        self.gridLayout_3.addWidget(self.label_upload_HDA, 1, 1, 1, 1)
        self.button_add_menu = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_menu.setText("")
        self.button_add_menu.setIconSize(QtCore.QSize(36, 36))
        self.button_add_menu.setFlat(True)
        self.button_add_menu.setObjectName("button_add_menu")
        self.gridLayout_3.addWidget(self.button_add_menu, 0, 2, 1, 1)
        self.label_save = QtWidgets.QLabel(self.centralwidget)
        self.label_save.setAlignment(QtCore.Qt.AlignCenter)
        self.label_save.setObjectName("label_save")
        self.gridLayout_3.addWidget(self.label_save, 1, 4, 1, 1)
        self.button_upload_HDA = QtWidgets.QPushButton(self.centralwidget)
        self.button_upload_HDA.setText("")
        self.button_upload_HDA.setIconSize(QtCore.QSize(36, 36))
        self.button_upload_HDA.setFlat(True)
        self.button_upload_HDA.setObjectName("button_upload_HDA")
        self.gridLayout_3.addWidget(self.button_upload_HDA, 0, 1, 1, 1)
        self.label_add_HDA = QtWidgets.QLabel(self.centralwidget)
        self.label_add_HDA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_HDA.setObjectName("label_add_HDA")
        self.gridLayout_3.addWidget(self.label_add_HDA, 1, 0, 1, 1)
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setText("")
        self.button_delete.setIconSize(QtCore.QSize(36, 36))
        self.button_delete.setFlat(True)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout_3.addWidget(self.button_delete, 0, 3, 1, 1)
        self.label_delete = QtWidgets.QLabel(self.centralwidget)
        self.label_delete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delete.setObjectName("label_delete")
        self.gridLayout_3.addWidget(self.label_delete, 1, 3, 1, 1)
        self.button_update = QtWidgets.QPushButton(self.centralwidget)
        self.button_update.setText("")
        self.button_update.setIconSize(QtCore.QSize(36, 36))
        self.button_update.setFlat(True)
        self.button_update.setObjectName("button_update")
        self.gridLayout_3.addWidget(self.button_update, 0, 6, 1, 1)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setText("")
        self.button_save.setIconSize(QtCore.QSize(36, 36))
        self.button_save.setFlat(True)
        self.button_save.setObjectName("button_save")
        self.gridLayout_3.addWidget(self.button_save, 0, 4, 1, 1)
        self.button_shelf_backup = QtWidgets.QPushButton(self.centralwidget)
        self.button_shelf_backup.setText("")
        self.button_shelf_backup.setIconSize(QtCore.QSize(36, 36))
        self.button_shelf_backup.setFlat(True)
        self.button_shelf_backup.setObjectName("button_shelf_backup")
        self.gridLayout_3.addWidget(self.button_shelf_backup, 0, 7, 1, 1)
        self.label_shelf_backup = QtWidgets.QLabel(self.centralwidget)
        self.label_shelf_backup.setObjectName("label_shelf_backup")
        self.gridLayout_3.addWidget(self.label_shelf_backup, 1, 7, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.contol_hbox = QtWidgets.QHBoxLayout()
        self.contol_hbox.setSpacing(15)
        self.contol_hbox.setObjectName("contol_hbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.radio_button_user = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_user.setObjectName("radio_button_user")
        self.horizontalLayout_3.addWidget(self.radio_button_user)
        self.radio_button_show = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_button_show.sizePolicy().hasHeightForWidth())
        self.radio_button_show.setSizePolicy(sizePolicy)
        self.radio_button_show.setChecked(True)
        self.radio_button_show.setObjectName("radio_button_show")
        self.horizontalLayout_3.addWidget(self.radio_button_show)
        self.radio_button_base = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_base.setObjectName("radio_button_base")
        self.horizontalLayout_3.addWidget(self.radio_button_base)
        self.contol_hbox.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.contol_hbox.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_cbbox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_cbbox.sizePolicy().hasHeightForWidth())
        self.project_cbbox.setSizePolicy(sizePolicy)
        self.project_cbbox.setMinimumSize(QtCore.QSize(0, 0))
        self.project_cbbox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.project_cbbox.setObjectName("project_cbbox")
        self.horizontalLayout_2.addWidget(self.project_cbbox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.city_cbbox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_cbbox.sizePolicy().hasHeightForWidth())
        self.city_cbbox.setSizePolicy(sizePolicy)
        self.city_cbbox.setObjectName("city_cbbox")
        self.horizontalLayout_2.addWidget(self.city_cbbox)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.contol_hbox.addLayout(self.horizontalLayout)
        self.contol_hbox.setStretch(0, 2)
        self.contol_hbox.setStretch(1, 1)
        self.contol_hbox.setStretch(2, 6)
        self.verticalLayout.addLayout(self.contol_hbox)
        self.label = QtWidgets.QVBoxLayout()
        self.label.setObjectName("label")
        self.verticalLayout.addLayout(self.label)
        self.tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_widget.setDragEnabled(True)
        self.tree_widget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tree_widget.setAlternatingRowColors(True)
        self.tree_widget.setAnimated(True)
        self.tree_widget.setWordWrap(True)
        self.tree_widget.setObjectName("tree_widget")
        self.verticalLayout.addWidget(self.tree_widget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_HDA = QtWidgets.QAction(MainWindow)
        self.action_add_HDA.setCheckable(False)
        self.action_add_HDA.setObjectName("action_add_HDA")
        self.action_upload_hip = QtWidgets.QAction(MainWindow)
        self.action_upload_hip.setCheckable(False)
        font = QtGui.QFont()
        self.action_upload_hip.setFont(font)
        self.action_upload_hip.setObjectName("action_upload_hip")
        self.action_add_menu = QtWidgets.QAction(MainWindow)
        self.action_add_menu.setObjectName("action_add_menu")
        self.action_delete = QtWidgets.QAction(MainWindow)
        self.action_delete.setObjectName("action_delete")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_upload_shelf = QtWidgets.QAction(MainWindow)
        self.action_upload_shelf.setObjectName("action_upload_shelf")
        self.action_update = QtWidgets.QAction(MainWindow)
        self.action_update.setObjectName("action_update")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ToolSet Manager", None))
        self.label_add_menu.setText(_translate("MainWindow", "Add Menu", None))
        self.label_help.setText(_translate("MainWindow", "Help", None))
        self.label_delete.setText(_translate("MainWindow", "Delete", None))
        self.label_save.setText(_translate("MainWindow", "Save", None))
        self.label_update.setText(_translate("MainWindow", "Update", None))
        self.label_upload_HDA.setText(_translate("MainWindow", "Upload HDA", None))
        self.label_add_HDA.setText(_translate("MainWindow", "Add HDA", None))
        self.label_shelf_backup.setText(_translate("MainWindow", "Shelf Backup", None))
        self.label_2.setText(_translate("MainWindow", "Mode:", None))
        self.radio_button_user.setText(_translate("MainWindow", "user", None))
        self.radio_button_show.setText(_translate("MainWindow", "show", None))
        self.radio_button_base.setText(_translate("MainWindow", "base", None))
        self.label_4.setText(_translate("MainWindow", "City:", None))
        self.tree_widget.setSortingEnabled(True)
        self.tree_widget.headerItem().setText(0, _translate("MainWindow", "Name", None))
        self.tree_widget.headerItem().setText(1, _translate("MainWindow", "Type", None))
        self.tree_widget.headerItem().setText(2, _translate("MainWindow", "Author", None))
        self.tree_widget.headerItem().setText(3, _translate("MainWindow", "About", None))
        self.action_add_HDA.setText(_translate("MainWindow", "Add HDA", None))
        self.action_add_HDA.setToolTip(_translate("MainWindow", "upload selected node or HDA", None))
        self.action_upload_hip.setText(_translate("MainWindow", "Upload hip", None))
        self.action_upload_hip.setToolTip(_translate("MainWindow", "Upload hip", None))
        self.action_add_menu.setText(_translate("MainWindow", "Add Menu", None))
        self.action_delete.setText(_translate("MainWindow", "Delete", None))
        self.action_save.setText(_translate("MainWindow", "Save", None))
        self.action_help.setText(_translate("MainWindow", "Help", None))
        self.action_upload_shelf.setText(_translate("MainWindow", "Upload shelf", None))
        self.action_upload_shelf.setToolTip(_translate("MainWindow", "upload shelf", None))
        self.action_update.setText(_translate("MainWindow", "Update", None))
